name: learn_maps
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # learn
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter_android: ^2.1.10
  google_maps_flutter_platform_interface: ^2.2.1

  espresso: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/locations.json
    - assets/images/img.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
